src/Entity/PhoneNumber.php
<?php

namespace App\Entity;

use App\Repository\PhoneNumberRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhoneNumberRepository::class)
 */
class PhoneNumber
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone_no;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="phoneNumbers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoneNo(): ?string
    {
        return $this->phone_no;
    }

    public function setPhoneNo(string $phone_no): self
    {
        $this->phone_no = $phone_no;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date")
     */
    private $dob;

    /**
     * @ORM\Column(type="integer")
     */
    private $u_name;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="user", orphanRemoval=true)
     */
    private $addresses;

    /**
     * @ORM\OneToMany(targetEntity=PhoneNumber::class, mappedBy="user", orphanRemoval=true)
     */
    private $phoneNumbers;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->phoneNumbers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDob(): ?\DateTimeInterface
    {
        return $this->dob;
    }

    public function setDob(\DateTimeInterface $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    public function getUName(): ?int
    {
        return $this->u_name;
    }

    public function setUName(int $u_name): self
    {
        $this->u_name = $u_name;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PhoneNumber[]
     */
    public function getPhoneNumbers(): Collection
    {
        return $this->phoneNumbers;
    }

    public function addPhoneNumber(PhoneNumber $phoneNumber): self
    {
        if (!$this->phoneNumbers->contains($phoneNumber)) {
            $this->phoneNumbers[] = $phoneNumber;
            $phoneNumber->setUser($this);
        }

        return $this;
    }

    public function removePhoneNumber(PhoneNumber $phoneNumber): self
    {
        if ($this->phoneNumbers->removeElement($phoneNumber)) {
            // set the owning side to null (unless already changed)
            if ($phoneNumber->getUser() === $this) {
                $phoneNumber->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\CallbackTransformer;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('roles', ChoiceType::class, [
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices' => [
                    'User' => 'ROLE_USER',
                    'Admin' => 'ROLE_ADMIN',
                ],
            ])
            ->add('password')
            ->add('first_name')
            ->add('last_name')
            ->add('dob')
            ->add('u_name');

        $builder->get('roles')->addModelTransformer(new CallbackTransformer(
            function ($rolesArray) {
                return count($rolesArray) ? $rolesArray[0] : null;
            }, function ($roleString) {
            return [$roleString];
        }
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Backend/UserController.php
<?php

namespace App\Controller\Backend;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend/users")
 */
class UserController extends AbstractController
{
    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(Request $request, UserRepository $userRepository): Response
    {

        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findByKeyWord($request->get('keyword')),
            'keyword' => $request->get('keyword'),
        ]);
    }

    /**
     * @Route("/create", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        if ($request->getMethod() == "POST") {
            $data = [];
            $data['first_name'] = $request->get('first_name');
            $data['last_name'] = $request->get('last_name');
            $data['email'] = $request->get('email');
            $data['password'] = $request->get('password');
            $data['dob'] = $request->get('dob');
            $data['address'] = $request->get('address');
            $data['phone'] = $request->get('phone');
            $data['roles'] = $request->get('roles');
            if (empty($data['first_name']) || empty($data['last_name']) || empty($data['email']) || empty($data['dob']) || empty($data['password']) || empty($data['roles']) || count($data['phone']) == 0 || count($data['address']) == 0) {
                $this->addFlash('error', 'Please fill all required fields.');
                return $this->redirectToRoute('user_new');
            }
            $this->userRepository->store($data);
            $this->addFlash('success', 'User created successfully');
            return $this->redirectToRoute('user_index');

        }
        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        $addresses = $user->getAddresses();
        $phoneNumbers = $user->getPhoneNumbers();
        return $this->render('user/show.html.twig', [
            'user' => $user,
            'addresses' => $addresses,
            'phone_numbers' => $phoneNumbers,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($request->getMethod() == "POST") {
            $data = [];
            $data['first_name'] = $request->get('first_name');
            $data['last_name'] = $request->get('last_name');
            $data['email'] = $request->get('email');
            $data['password'] = $request->get('password');
            $data['dob'] = $request->get('dob');
            $data['address'] = $request->get('address');
            $data['phone'] = $request->get('phone');
            $data['roles'] = $request->get('roles');
            if (empty($data['first_name']) || empty($data['last_name']) || empty($data['email']) || empty($data['dob'])) {
                $this->addFlash('error', 'Please fill all required fields.');
                return $this->redirectToRoute('user_new');
            }
            $this->userRepository->update($user, $data);
            $this->addFlash('success', 'User updated successfully');
            return $this->redirectToRoute('user_index');

        }
        $addresses = $user->getAddresses();
        $phoneNumbers = $user->getPhoneNumbers();
        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'addresses' => $addresses,
            'phone_numbers' => $phoneNumbers,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($user);
        $entityManager->flush();
        return new JsonResponse(['status' => 'User Deleted!'], Response::HTTP_OK);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit User</h1>
                </div>
                <div class="col-sm-6">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    {% include 'partials/alerts.html.twig' %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">Edit User</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form name="user" method="post">
                            <input type="hidden" name="token" value="{{ csrf_token('user') }}"/>
                            <div class="row mb-3">
                                <label for="first_name" class="col-sm-2 col-form-label">First Name</label>
                                <div class="col-sm-10">
                                    <input type="text" name="first_name" class="form-control col-md-6" id="first_name"
                                           placeholder="First Name" value="{{ user.FirstName }}" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="last_name" class="col-sm-2 col-form-label">Last Name</label>
                                <div class="col-sm-10">
                                    <input type="text" name="last_name" class="form-control col-md-6" id="last_name"
                                           placeholder="Last Name" value="{{ user.LastName }}" required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="email" class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" name="email" value="{{ user.email }}"
                                           class="form-control col-md-6" id="email"
                                           placeholder="Email"
                                           required>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="password" class="col-sm-2 col-form-label">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" name="password" class="form-control col-md-6" id="password"
                                           placeholder="password">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="password" class="col-sm-2 col-form-label">Roles</label>
                                <div class="col-sm-10">
                                    <select name="roles" class="form-control col-md-6" id="" required>
                                        {% if "ROLE_ADMIN" in user.roles %}
                                            <option value="ROLE_ADMIN" selected>Admin</option>
                                            <option value="ROLE_USER">User</option>
                                        {% elseif "ROLE_USER" in user.roles %}
                                            <option value="ROLE_ADMIN">Admin</option>
                                            <option value="ROLE_USER" selected>User</option>
                                        {% endif %}
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="dob" class="col-sm-2 col-form-label">Data of birth</label>
                                <div class="col-sm-10">
                                    <input type="date" name="dob" value="{{ user.dob| date("Y-m-d") }}"
                                           class="form-control col-md-6" id="dob" required>
                                </div>
                            </div>
                            <hr class="mt-2 mb-3"/>
                            <h4 class="mb-3">Addresses
                                <button type="button" class="btn btn-success float-right add-address-btn">Add</button>
                            </h4>
                            <div class="addresses-container mb-5" data-address="1">
                                {% for address in addresses %}
                                    <div class="row g-3 address-row mb-2">
                                        <div class="col">
                                            <input type="text" class="form-control street"
                                                   placeholder="Street" value="{{ address.street }}" required>
                                        </div>
                                        <div class="col">
                                            <input type="number" class="form-control zip"
                                                   placeholder="Zip" value="{{ address.zip }}" required>
                                        </div>
                                        <div class="col">
                                            <input type="text" class="form-control city"
                                                   placeholder="City" value="{{ address.city }}" required>
                                        </div>
                                        <div class="col">
                                            <input type="text" class="form-control country"
                                                   placeholder="Country" value="{{ address.country }}" required>
                                        </div>
                                        <div class="col">
                                            <button type="button"
                                                    data-edit-url="{{ path('address_edit',{id: address.id}) }}"
                                                    class="btn btn-info update-address-btn">update
                                            </button>
                                            <button type="button"
                                                    data-delete-url="{{ path('address_delete',{id: address.id}) }}"
                                                    class="btn btn-danger delete-address-btn">Delete
                                            </button>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                            <hr class="mt-2 mb-3"/>
                            <h4 class="mb-3">Phone Numbers
                                <button type="button" class="btn btn-success float-right add-phone-btn">Add</button>
                            </h4>
                            <div class="phone-container" data-phone="1">
                                {% for phone in phone_numbers %}

                                    <div class="row g-3 phone-row mb-2">
                                        <div class="col">
                                            <input type="text" class="form-control phone_no"
                                                   placeholder="Phone Number" value="{{ phone.phoneNo }}" required>
                                        </div>
                                        <div class="col">
                                            <button type="button"
                                                    data-edit-url="{{ path('phone_edit',{id: phone.id}) }}"
                                                    class="btn btn-info update-phone-btn">update
                                            </button>
                                            <button type="button"
                                                    data-delete-url="{{ path('phone_delete',{id: phone.id}) }}"
                                                    class="btn btn-danger delete-phone-btn">Delete
                                            </button>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="row">
                                <div class="col mt-5">
                                    <a href="{{ path('user_index') }}" class="btn btn-warning  float-right">Cancel</a>
                                    <button type="submit" class="btn btn-primary  float-right mr-2">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </section>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>User Detail</h1>
                </div>
                <div class="col-sm-6">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">User Detail</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>First Name: </b>{{ user.FirstName }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Last Name: </b>{{ user.LastName }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Email: </b>{{ user.email }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Username: </b>{{ user.UName }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>DOB: </b>{{ user.dob| date("Y-m-d") }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Created At: </b>{{ user.createdAt| date("Y-m-d H:i:s") }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Updated At: </b>{{ user.updatedAt| date("Y-m-d  H:i:s") }}</p>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-10">
                                <p class="text-muted"><b>Phone Numbers: </b></p>
                                {% for phone in phone_numbers %}
                                    <p class="text-muted">{{ phone.phoneNo }}</p>
                                {% endfor %}
                            </div>
                        </div>
                        <hr class="mt-2 mb-3"/>
                        <h5 class="mb-3">Addresses</h5>
                        <div class="addresses-container mb-5" data-address="1">
                            <div class="row g-3 address-row mb-2">
                                {% for address in addresses %}
                                    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                                        <div class="card bg-light d-flex flex-fill">
                                            <div class="card-body pt-0">
                                                <div class="row">
                                                    <div class="col pt-3">
                                                        <p class="text-muted"><b>Street: </b>{{ address.street }}</p>
                                                        <p class="text-muted"><b>Zip: </b>{{ address.zip }}</p>
                                                        <p class="text-muted"><b>City: </b>{{ address.city }}</p>
                                                        <p class="text-muted"><b>Country: </b>{{ address.country }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                        </div>
                        <div class="row">
                            <div class="col mt-5">
                                <a href="{{ path('user_index') }}" class="btn btn-warning  float-right">Back</a>
                                <a href="{{ path('user_edit',{id:user.id}) }}" class="btn btn-primary  float-right mr-2">Edit</a>
                            </div>
                        </div>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>

    </section>

{% endblock %}